calculateFunFactor: testBookings.o
	g++ -g -o testCalculateFunFactor.cpp testCalculateFunFactor.o -lcppunit

testCalculateFunFactor: testCalculateFunFactor.cpp Graphkings.h
	g++ -g -c testCalculateFunFactor.cpp -lcppunit
 
clean:
	echo : "clean"
	rm testCalculateFunFactor.o testCalculateFunFactor